### ISSUE TITLE
hf-xet Requirements missmatch

### ISSUE THREAD

**Issue by 0Falli0** [huggingface/huggingface_hub#3239]
### Describe the bug

The requirements for the hf-xet extra are still needed even though the extra is no longer defined as such.

pkg_resources.VersionConflict: (huggingface-hub 0.33.1 (/.pyenv/versions/3.11.13/lib/python3.11/site-packages), Requirement.parse('huggingface-hub[hf-xet]==0.33.4'))

### Logs

```shell

```

### System info

```shell
- huggingface_hub version: 0.33.1
- Platform: Linux-6.8.0-62-generic-x86_64-with-glibc2.35
- Python version: 3.11.13
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Running in Google Colab Enterprise ?: No
- Token path ?: /root/.cache/huggingface/token
- Has saved token ?: False
- Configured git credential helpers: 
- FastAI: N/A
- Tensorflow: N/A
- Torch: 2.7.0
- Jinja2: 3.1.6
- Graphviz: N/A
- keras: N/A
- Pydot: N/A
- Pillow: 10.4.0
- hf_transfer: N/A
- gradio: N/A
- tensorboard: N/A
- numpy: 1.26.4
- pydantic: 2.11.7
- aiohttp: 3.10.5
- hf_xet: 1.1.5
- ENDPOINT: https://huggingface.co
- HF_HUB_CACHE: /root/.cache/huggingface/hub
- HF_ASSETS_CACHE: /root/.cache/huggingface/assets
- HF_TOKEN_PATH: /root/.cache/huggingface/token
- HF_STORED_TOKENS_PATH: /root/.cache/huggingface/stored_tokens
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
- HF_HUB_ETAG_TIMEOUT: 10
- HF_HUB_DOWNLOAD_TIMEOUT: 10
```

**Comment by 0Falli0** [comment]
Steps to reproduce:
poetry export --without-hashes --format=requirements.txt > requirements.txt
liccheck -s liccheck.ini -r requirements.txt

**Comment by 0Falli0** [comment]
liccheck version: 0.9.2
https://pypi.org/project/liccheck/

**Comment by Wauplin** [comment]
hi @0Falli0 could you try to install and reinstall? might be something happening in your venv.

```
pip uninstall -y hf_xet
pip uninstall -y huggingface_hub
pip install -U huggingface_hub
```

**Comment by 0Falli0** [comment]
Unfortunately I've already tried this and it did not bring any improvements.

**Comment by Wauplin** [comment]
~Should have been fixed by @hanouticelina in https://github.com/huggingface/huggingface_hub/pull/3251. Fix will be shipped soon :)~

**Comment by Tanishq1030** [comment]
Hi! I'd like to help fix this issue.

I noticed PR #3251 was mentioned, but it addresses Python 3.13 docstring compatibility - not the `hf-xet` version mismatch reported here. The issue is still present in the current codebase.

**Root cause in [setup.py](cci:7://file:///d:/huggingface_hub/setup.py:0:0-0:0):**
- **Line 19** (base `install_requires`): `hf-xet>=1.2.0,<2.0.0`
- **Line 48** (`extras["hf_xet"]`): `hf-xet>=1.1.3,<2.0.0`

This version mismatch causes conflicts when installing `huggingface-hub[hf_xet]`.

**Proposed fix:**
```python
# Line 48 - align with base requirement
extras["hf_xet"] = ["hf-xet>=1.2.0,<2.0.0"]
```

I'm happy to submit a PR with this one-line fix if that works for you. Let me know!

Would you like me to go ahead and create a branch + implement the fix?

**Comment by Wauplin** [comment]
> **Proposed fix:**
> ```python
> # Line 48 - align with base requirement
> extras["hf_xet"] = ["hf-xet>=1.2.0,<2.0.0"]
> ```

Thanks for proposing your help @Tanishq1030! This is actually the correct fix to apply yes. To avoid any consistency issue in the future, could you define `"hf-xet>=1.2.0,<2.0.0"` as a string variable and then reuse it in both the required dependencies (with the extra OS check) and in the `hf_xet` optional dependency. Doing so should avoid updating one but not the other in the future ^^

Let me know when you want a PR review!

**Comment by Tanishq1030** [comment]
Hi @Wauplin! 

I've implemented the fix following your suggestion. 

**PR:** #3662 

### Changes Made:
- Created `HF_XET_VERSION = "hf-xet>=1.2.0,<2.0.0"` variable
- Used it in both `install_requires` (with platform check) and `extras["hf_xet"]`

This implements the DRY principle you suggested and ensures version consistency.

### Tested:
✅ `pip install -e .` - works without conflicts  
✅ `pip install -e ".[hf_xet]"` - works without conflicts  
✅ Both install `hf-xet 1.2.0` (verified with `pip show hf-xet`)

Ready for review!

**Comment by Wauplin** [comment]
Wonderful! I've reviewed and merged the PR :)

**Comment by Wauplin** [comment]
Just released `huggingface_hub` v1.2.4 with this fix :hugs:
https://github.com/huggingface/huggingface_hub/releases/tag/v1.2.4
