### ISSUE TITLE
Can't download large dataset with huggingface-cli or snapshot_download

### ISSUE THREAD

**Issue by JiarunLiu** [huggingface/huggingface_hub#3240]
### Describe the bug

Hi, I'm recently trying to download a dataset from [https://huggingface.co/datasets/AnonRes/OpenMind](https://huggingface.co/datasets/AnonRes/OpenMind). However, I'm unable to download it with both `snapshot_download` or `huggingface-cli` as provided in the Logs section.

Currently I'm only able to download this dataset by git lfs command. However, it can be timely and may unable to resume from network interruption. I have tried I can download other datasets such as `perler/ppsurf` on both machine with huggingface-cli. Is there any solutions to download `AnonRes/OpenMind` dataset with `snapshot_download` or `huggingface-cli`?

### Reproduction

huggingface-cli download AnonRes/OpenMind --repo-type dataset --resume-download --local-dir .

### Logs

```shell
### Machine-1

(hf) jiarunliu@server:/mnt/disk1/OpenMind$ python
Python 3.9.23 (main, Jun  5 2025, 13:40:20) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from huggingface_hub import snapshot_download
>>> import os
>>> snapshot_download(
...   repo_id="AnonRes/OpenMind",
...   repo_type="dataset",
...   local_dir="/mnt/disk1/OpenMind",
...   max_workers=8,
... )
Fetching 0 files: 0it [00:00, ?it/s]
'/mnt/disk1/OpenMind'
>>> os.listdir("/mnt/disk1/OpenMind")
[]
>>> import huggingface_hub
>>> huggingface_hub.__version__
'0.33.4'
>>> exit()

(hf) jiarunliu@server:/mnt/disk1/OpenMind$ huggingface-cli download AnonRes/OpenMind --repo-type dataset --resume-download --local-dir .
Fetching 0 files: 0it [00:00, ?it/s]
/mnt/disk1/jiarunliu/Stroke/datasets/OpenMind
(hf) jiarunliu@server:/mnt/disk1/OpenMind$ ls

(hf) jiarunliu@server:/mnt/disk1/OpenMind$ huggingface-cli version
huggingface_hub version: 0.30.2

### Machine-2


(hf1) jiarunliu@fgldlb:/mnt/disk1/OpenMind$ python
Python 3.9.12 (main, Apr  5 2022, 06:56:58) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from huggingface_hub import snapshot_download
>>> import os
>>> snapshot_download(
...   repo_id="AnonRes/OpenMind",
...   repo_type="dataset",
...   local_dir="/mnt/disk1/OpenMind",
...   max_workers=8,
... )

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.9/site-packages/huggingface_hub/_snapshot_download.py", line 245, in snapshot_download
    assert repo_info.siblings is not None, "Repo info returned from server must have a siblings list."
AssertionError: Repo info returned from server must have a siblings list.
>>> 
>>> os.listdir("/mnt/disk1/OpenMind")
[]
>>> import huggingface_hub
>>> huggingface_hub.__version__
'0.23.2'
>>> exit()
(hf1) jiarunliu@fgldlb:/mnt/disk1/OpenMind$ huggingface-cli download AnonRes/OpenMind --repo-type dataset --resume-download --local-dir .
Traceback (most recent call last):
  File "/usr/local/anaconda3/bin/huggingface-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/anaconda3/lib/python3.9/site-packages/huggingface_hub/commands/huggingface_cli.py", line 51, in main
    service.run()
  File "/usr/local/anaconda3/lib/python3.9/site-packages/huggingface_hub/commands/download.py", line 146, in run
    print(self._download())  # Print path to downloaded files
  File "/usr/local/anaconda3/lib/python3.9/site-packages/huggingface_hub/commands/download.py", line 180, in _download
    return snapshot_download(
  File "/usr/local/anaconda3/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.9/site-packages/huggingface_hub/_snapshot_download.py", line 245, in snapshot_download
    assert repo_info.siblings is not None, "Repo info returned from server must have a siblings list."
AssertionError: Repo info returned from server must have a siblings list.
```

### System info

```shell
# Machine-1:
- huggingface_hub version: 0.30.2
- Platform: Linux-5.15.0-130-generic-x86_64-with-glibc2.35
- Python version: 3.12.4
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Running in Google Colab Enterprise ?: No
- Token path ?: /home/jiarunliu/.cache/huggingface/token
- Has saved token ?: True
- Who am I ?: fgldlb
- Configured git credential helpers: 
- FastAI: N/A
- Tensorflow: N/A
- Torch: N/A
- Jinja2: 3.1.4
- Graphviz: N/A
- keras: N/A
- Pydot: N/A
- Pillow: 10.3.0
- hf_transfer: N/A
- gradio: N/A
- tensorboard: N/A
- numpy: 1.26.4
- pydantic: 2.5.3
- aiohttp: 3.9.5
- hf_xet: N/A
- ENDPOINT: https://hf-mirror.com
- HF_HUB_CACHE: /home/jiarunliu/.cache/huggingface/hub
- HF_ASSETS_CACHE: /home/jiarunliu/.cache/huggingface/assets
- HF_TOKEN_PATH: /home/jiarunliu/.cache/huggingface/token
- HF_STORED_TOKENS_PATH: /home/jiarunliu/.cache/huggingface/stored_tokens
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
- HF_HUB_ETAG_TIMEOUT: 10
- HF_HUB_DOWNLOAD_TIMEOUT: 10

# Machine-2:
- huggingface_hub version: 0.23.2
- Platform: Linux-5.15.0-43-generic-x86_64-with-glibc2.35
- Python version: 3.9.12
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /home/fgldlb/.cache/huggingface/token
- Has saved token ?: True
- Configured git credential helpers: 
- FastAI: N/A
- Tensorflow: N/A
- Torch: N/A
- Jinja2: 2.11.3
- Graphviz: N/A
- keras: N/A
- Pydot: N/A
- Pillow: 9.0.1
- hf_transfer: N/A
- gradio: N/A
- tensorboard: N/A
- numpy: 1.21.5
- pydantic: 2.8.0
- aiohttp: 3.8.1
- ENDPOINT: https://huggingface.co
- HF_HUB_CACHE: /home/fgldlb/.cache/huggingface/hub
- HF_ASSETS_CACHE: /home/fgldlb/.cache/huggingface/assets
- HF_TOKEN_PATH: /home/fgldlb/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
- HF_HUB_ETAG_TIMEOUT: 10
- HF_HUB_DOWNLOAD_TIMEOUT: 10
```

**Comment by Wauplin** [comment]
Hi @JiarunLiu , sorry for the inconvenience. It's usually better to upgrade `huggingface_hub` version to latest (latest is 0.33.4, so 0.23.2 and 0.30.2 are quite outdated). I pushed a new fix that should prevent the issue you are having (see https://github.com/huggingface/huggingface_hub/pull/3241).

Note that the issue comes from the fact that https://huggingface.co/datasets/AnonRes/OpenMind is a pathological dataset repo with 450k+ files in it. This is far from ideal as it makes the whole repo very slow to work with. [The recommended limit is 100k files per repo](https://huggingface.co/docs/hub/storage-limits#recommendations) to ensure good user experience. A good thing to do would be to try to contact the authors to suggest them to reduce the number of files in the repo, typically by grouping files. Large datasets are often uploaded as parquet with 1 row == 1 data point (can be text, image, mask, etc.) to group data together and reduce repo size. You can contact the authors in the repo discussion page: https://huggingface.co/datasets/AnonRes/OpenMind/discussions

**Comment by JiarunLiu** [comment]
Hi @Wauplin, I have tried to update my `huggingface_hub` to latest (0.33.4), but the issue remain. I'll use `git lfs` or contact the authors. Thank you.

**Comment by Wauplin** [comment]
Hi @JiarunLiu if you [install from source](https://huggingface.co/docs/huggingface_hub/installation#install-from-source) from my branch, it will work:

```
pip install git+https://github.com/huggingface/huggingface_hub@3240-fix-snapshot-download-0-files
```

**Comment by JiarunLiu** [comment]
@Wauplin You are right, it's worked when install from source. Thank you.

**Comment by Wauplin** [comment]
Glad to hear that! 🤗
