### ISSUE TITLE
Text-generation API endpoint fails to handle integer-formatted numeric arguments in JSON request

### ISSUE THREAD

**Issue by benjismith** [huggingface/huggingface_hub#541]
When I call the hosted text-generation API, the request fails if I set the `temperature` parameter to an integer value of `1` instead of a float value of `1.0`.

For example, this succeeds:

```
curl -i -X POST https://api-inference.huggingface.co/models/my_organization/my_model \
     -H "Authorization: Bearer <<REDACTED>>" \
     -H "Content-Type: application/json" \
     -d \
     '{
          "inputs":"Once upon a time",
          "parameters": {
            "temperature": 1.0,
            "max_new_tokens": 20
          }
     }'
```

But this request fails:

```
curl -i -X POST https://api-inference.huggingface.co/models/my_organization/my_model \
     -H "Authorization: Bearer <<REDACTED>>" \
     -H "Content-Type: application/json" \
     -d \
     '{
          "inputs":"Once upon a time",
          "parameters": {
            "temperature": 1,
            "max_new_tokens": 20
          }
     }'
```

...with this error message:

```
{"error":["value is not a valid float: `temperature` in `parameters`"]}
```

Both requests should succeed. The only difference between the two requests is the numeric formatting of the `temperature` parameter (with or without a decimal point and trailing zero).

**Comment by Narsil** [comment]
Hi @benjismith , thanks for reporting.

This is now fixed ! Can you confirm before I close ?

**Comment by benjismith** [comment]
I'm still seeing the same behavior on my private model `shaxpir/prosecraft_resumed_ft2`
