### ISSUE TITLE
PyTorchModelHubMixin doesn't work when pushing to the hub several times

### ISSUE THREAD

**Issue by NielsRogge** [huggingface/huggingface_hub#829]
The `PyTorchModelHubMixin` doesn't work when regularly pushing the model to the hub, let's say every epoch.

At some point, your notebook or script will fail with the following error:

```
CalledProcessError                        Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/huggingface_hub/repository.py](https://localhost:8080/#) in git_push(self, upstream, blocking, auto_lfs_prune)
   1201                         raise subprocess.CalledProcessError(
-> 1202                             return_code, process.args, output=stdout, stderr=stderr
   1203                         )

CalledProcessError: Command '['git', 'push']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
2 frames
[/usr/local/lib/python3.7/dist-packages/huggingface_hub/repository.py](https://localhost:8080/#) in git_push(self, upstream, blocking, auto_lfs_prune)
   1204 
   1205         except subprocess.CalledProcessError as exc:
-> 1206             raise EnvironmentError(exc.stderr)
   1207 
   1208         if not blocking:

OSError: batch response: Client error: https://huggingface.co/nielsr/test.git/info/lfs/objects/batch from HTTP 405
error: failed to push some refs to 'https://huggingface.co/nielsr/test'
```

I've created a minimal Colab notebook to reproduce: https://colab.research.google.com/drive/1Ao5ud6Wa1JAORHauexvtrdl0-VYITuMK?usp=sharing

Weirdly, it works for the first few epochs, but then fails at some point.

**Comment by NielsRogge** [comment]
Relevant to #321

**Comment by julien-c** [comment]
could be rate-limiting no? @XciD

**Comment by XciD** [comment]
> could be rate-limiting no? @XciD

Yes, I've deployed new rules in the firewall, can you retry?

**Comment by NielsRogge** [comment]
Doesn't work for me, I'm still getting:

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "/home/niels/python_projects/community-events-1/huggan/pytorch/pix2pix/train.py", line 300, in <module>
    main()
  File "/home/niels/python_projects/community-events-1/huggan/pytorch/pix2pix/train.py", line 296, in main
    training_function({}, args)
  File "/home/niels/python_projects/community-events-1/huggan/pytorch/pix2pix/train.py", line 285, in training_function
    unwrapped_generator.push_to_hub(
  File "/home/niels/python_projects/community-events-1/huggan/pytorch/huggan_mixin.py", line 131, in push_to_hub
    return repo.git_push()
  File "/home/niels/python_projects/community-events-1/env/lib/python3.9/site-packages/huggingface_hub/repository.py", line 1023, in git_push
    raise EnvironmentError(exc.stderr)
OSError: remote: error: cannot lock ref 'refs/heads/main': is at 2e21479923ef5b988e189622bbf6a4ff26bd2a50 but expected bdecbbc9c3a19751d01de8d8b344bc583ec8e4aa        
To https://huggingface.co/huggan/pix2pix-maps-test
 ! [remote rejected] main -> main (failed to update ref)
error: failed to push some refs to 'https://huggingface.co/huggan/pix2pix-maps-test'
```

**Comment by NielsRogge** [comment]
Update: works fine for me now. 

Closing this issue, thanks for looking into it!
